### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by probonopd** [vlc-qt/packaging#1]
Have you found a way to make build time manageable? I tried to build VLC 3 on Travis CI before and always struggled with build time. I guess it could work by compiling each component (contribs) separately and in the end tie everything together.

**Comment by ntadej** [comment]
It takes around 3 min on clean build to make debs. That's completely ok in my opinion. Note that Travis builds need to install dependencies which will always be slower than directly on PC.

**Comment by probonopd** [comment]
That's more than OK - my builds (including the contribs) took more like, 2 hours

**Comment by ntadej** [comment]
You should build VLC separately and cache it somewhere to use with VLC-Qt.

**Comment by probonopd** [comment]
Yes, i see. Thank you! Where are you doing this?
